### ISSUE TITLE
Add Support for elliptic curve discrete logarithm post-processing

### ISSUE THREAD

**Issue by LukasMansour** [ekera/quaspy#1]
I believe it is already basically included, since the two register mosca-ekert version can be used for it (not 100% sure), but it is likely another reference and good to document which method to use.

https://arxiv.org/pdf/quant-ph/0301141 (Appendix A likely most important for you)

**Comment by ekera** [comment]
So Quaspy is basically agnostic to which group you use: It does not actually simulate the quantum circuit for the arithmetic. Rather it simulates the high-level quantum algorithms — and the only thing that matters then is what the order of the group is, what the logarithm is, how parameters are selected, etc. So support for what you ask for is already included.

Quaspy gives you the choice of using a concrete group for the arithmetic, or a simulated cyclic group. There is [support built-in](https://github.com/ekera/quaspy/tree/main/docs/math/groups) for short Weierstrass curves defined over prime fields. There is already an [example](https://colab.research.google.com/github/ekera/quaspy/blob/main/examples/logarithmfinding.ipynb) included for elliptic curve discrete logarithms, that uses the analysis and post-processing in [[E19p]](https://doi.org/10.48550/arXiv.1905.09084). It is accessible from [the examples directory](https://github.com/ekera/quaspy/tree/main/examples).

**Comment by LukasMansour** [comment]
As soon as I had asked the question, I found the example :P. I must say this package is incredible, is there anyway I can cite this piece of software (with an official DOI, else I will just link to your repository)? This has saved me a lot of head scratches for my implementation of ECDLP solving. Perhaps Zenodo or something similar?

Also, got a better understanding for the post-processing thanks to this library, honestly thank you for creating a good reference.

**Comment by ekera** [comment]
Thank you for your positive feedback. I am glad that you found Quaspy useful. I have not (yet) created a DOI for this repository. Perhaps I should do so, but for now, you can link to it by its URL here on GitHub. Feel free to also cite the relevant papers, and also to write me an e-mail if you are doing work related to Quaspy that you wish to share.

I will close the issue with this reply, since it has now been resolved.
